name: muslim_guide
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  appspector: ^0.7.0

  fimber: ^0.6.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  flutter_custom_clippers: ^1.1.2
  flutter_staggered_grid_view: ^0.4.0
  http: ^0.13.3
  auto_size_text: ^3.0.0-nullsafety.0

#  splashscreen: ^1.3.5
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.1
  json_serializable: ^4.1.4

  equatable: ^2.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  geolocator: ^7.4.0
  flutter_svg: ^0.22.0
  dio: ^4.0.0
  floor: ^1.1.0
  intl: ^0.17.0
  loading_overlay: ^0.3.0

dev_dependencies:
  flutter_native_splash: ^1.2.1
  pedantic: ^1.11.1
  build_runner: ^2.1.1
  floor_generator: ^1.1.0
  connectivity: ^3.0.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo3.png"

flutter_native_splash:

  background_image: assets/images/splash.png

  android_disable_fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/files/
    - google_fonts/
  fonts:
    - family: Me Quran
      fonts:
        - asset: google_fonts/me_quran.ttf

